# Site Settings
title: Amir Lab
tagline: Cloud Security | Linux | DevOps | Walkthroughs
description: A minimal, responsive, feature-rich Jekyll theme for technical writing.
lang: en
timezone: Asia/Kuala_Lumpur

# URLs for GitHub Pages
url: "https://amirqusairy99.github.io"  # your site URL
baseurl: ""  # keep empty for user page

# GitHub / Social
github:
  username: amirqusairy99

social:
  name: Amir Qusairy
  email: amirqusairy7@gmail.com
  links:
    - https://twitter.com/amirqusairy99
    - https://github.com/amirqusairy99

# Theme
theme: jekyll-theme-chirpy
theme_mode: ""  # leave empty to follow system preference

# Avatar & images
avatar: /assets/img/heroblack.png
social_preview_image: /assets/img/heroblack.png

# Posts and collections
paginate: 10
toc: true
collections:
  tabs:
    output: true
    sort_by: order

# Kramdown / Syntax highlighting
kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# PWA (optional)
pwa:
  enabled: true
  cache:
    enabled: true
    deny_paths: []

# Compress HTML
compress_html:
  clippings: all
  comments: all
  endings: all
  blanklines: false
  ignore:
    envs: [development]

# Exclude unnecessary files from build
exclude:
  - "*.gem"
  - "*.gemspec"
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - "*.config.js"
  - "package*.json"

# Jekyll Archives
jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
